# fly.toml app configuration file generated for langram-api on 2026-09-03T13:20:48-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'langram-api'
primary_region = 'ord'

[build]
[deploy]
  release_command = '/app/release.sh'

[env]
  LANGRAM_CORS_ORIGINS = '["https://ayter.com"]'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
