"""bkt state and skill opportunities

Revision ID: 005c2db72a74
Revises: 4bff675151cc
Create Date: 2026-08-31 22:49:08.809603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Autogenerate emits a bare Text() inside JSONB variants, so keep the name
# in scope rather than discovering it at migration time.
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '005c2db72a74'
down_revision: Union[str, Sequence[str], None] = '4bff675151cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False))

    with op.batch_alter_table('user_concept_mastery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_concept_mastery', schema=None) as batch_op:
        batch_op.drop_column('state')

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_column('skills')

    # ### end Alembic commands ###
