"""review cards carry the item spec

Revision ID: 4bff675151cc
Revises: a88c6195bec0
Create Date: 2026-08-31 12:49:25.116781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bff675151cc'
down_revision: Union[str, Sequence[str], None] = 'a88c6195bec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_cards', schema=None) as batch_op:
        batch_op.drop_column('item_spec')

    # ### end Alembic commands ###
