"""concept intro text and per-learner intro tracking

Revision ID: a309ab850d6b
Revises: 005c2db72a74
Create Date: 2026-09-03 09:44:23.740693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Autogenerate emits a bare Text() inside JSONB variants, so keep the name
# in scope rather than discovering it at migration time.
from sqlalchemy import Text  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'a309ab850d6b'
down_revision: Union[str, Sequence[str], None] = '005c2db72a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intro', sa.Text(), nullable=False, server_default=''))
        # The default is only a bridge for existing rows: the next `db.seed`
        # overwrites every concept's intro with real content from content/.

    with op.batch_alter_table('user_concept_mastery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intro_seen_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_concept_mastery', schema=None) as batch_op:
        batch_op.drop_column('intro_seen_at')

    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_column('intro')

    # ### end Alembic commands ###
