"""initial schema

Revision ID: a88c6195bec0
Revises: 
Create Date: 2026-08-31 01:27:04.464835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a88c6195bec0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lexemes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('lemma', sa.String(length=64), nullable=False),
    sa.Column('pos', sa.String(length=16), nullable=False),
    sa.Column('gloss', sa.Text(), nullable=False),
    sa.Column('frequency_band', sa.Integer(), nullable=True),
    sa.Column('properties', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lexemes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lexemes_lemma'), ['lemma'], unique=True)
        batch_op.create_index(batch_op.f('ix_lexemes_needs_review'), ['needs_review'], unique=False)

    op.create_table('suffixes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('archiphoneme_form', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('properties', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suffixes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suffixes_category'), ['category'], unique=False)

    op.create_table('units',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('research_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('prerequisites', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_index')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('native_language', sa.String(length=8), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('concepts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('unit_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('why_hard', sa.Text(), nullable=False),
    sa.Column('teaches_suffixes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concepts_unit_id'), ['unit_id'], unique=False)

    op.create_table('perception_trials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contrast_id', sa.String(length=64), nullable=False),
    sa.Column('talker_id', sa.String(length=64), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('perception_trials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_perception_trials_contrast_id'), ['contrast_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_perception_trials_user_id'), ['user_id'], unique=False)

    op.create_table('recordings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_word', sa.String(length=64), nullable=False),
    sa.Column('audio_url', sa.Text(), nullable=False),
    sa.Column('f1', sa.Float(), nullable=True),
    sa.Column('f2', sa.Float(), nullable=True),
    sa.Column('f0', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recordings_user_id'), ['user_id'], unique=False)

    op.create_table('review_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=24), nullable=False),
    sa.Column('item_ref', sa.String(length=96), nullable=False),
    sa.Column('fsrs_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_type', 'item_ref', name='uq_user_item')
    )
    with op.batch_alter_table('review_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_cards_due_at'), ['due_at'], unique=False)
        batch_op.create_index('ix_review_due', ['user_id', 'due_at'], unique=False)

    op.create_table('exercises',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('concept_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('generator', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_stage'), ['stage'], unique=False)

    op.create_table('user_concept_mastery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.String(length=64), nullable=False),
    sa.Column('ability_estimate', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'concept_id', name='uq_user_concept')
    )
    with op.batch_alter_table('user_concept_mastery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_concept_mastery_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_concept_mastery_user_id'), ['user_id'], unique=False)

    op.create_table('responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.String(length=96), nullable=True),
    sa.Column('concept_id', sa.String(length=64), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('raw_answer', sa.Text(), nullable=False),
    sa.Column('error_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responses_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responses_user_id'))
        batch_op.drop_index(batch_op.f('ix_responses_created_at'))
        batch_op.drop_index(batch_op.f('ix_responses_concept_id'))

    op.drop_table('responses')
    with op.batch_alter_table('user_concept_mastery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_concept_mastery_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_concept_mastery_concept_id'))

    op.drop_table('user_concept_mastery')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_stage'))
        batch_op.drop_index(batch_op.f('ix_exercises_concept_id'))

    op.drop_table('exercises')
    with op.batch_alter_table('review_cards', schema=None) as batch_op:
        batch_op.drop_index('ix_review_due')
        batch_op.drop_index(batch_op.f('ix_review_cards_due_at'))

    op.drop_table('review_cards')
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recordings_user_id'))

    op.drop_table('recordings')
    with op.batch_alter_table('perception_trials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_perception_trials_user_id'))
        batch_op.drop_index(batch_op.f('ix_perception_trials_contrast_id'))

    op.drop_table('perception_trials')
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepts_unit_id'))

    op.drop_table('concepts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('units')
    with op.batch_alter_table('suffixes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suffixes_category'))

    op.drop_table('suffixes')
    with op.batch_alter_table('lexemes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lexemes_needs_review'))
        batch_op.drop_index(batch_op.f('ix_lexemes_lemma'))

    op.drop_table('lexemes')
    # ### end Alembic commands ###
